### ISSUE TITLE
ImportError: module 'eplus_env.envs' has no attribute 'EplusEnv'

### ISSUE THREAD

**Issue by zgq91** [chenbq1234/Gnu-RL#1]
hi:
   The following error is reported when I execute the imit_ep.py program. "ImportError: module 'eplus_env.envs' has no attribute 'EplusEnv'
"

**Comment by bingqingchen** [comment]
Hi, 
A more update-to-date version of the repo is posted [here](https://github.com/INFERLab/Gnu-RL). Also, the error you got is from setting up the simulation environment, which I am using the implementation [here](https://github.com/zhangzhizza/Gym-Eplus).  You may want to verify you have successfully set-up the co-simulation environment with EnergyPlus before running my code.
