### ISSUE TITLE
How do you train your model

### ISSUE THREAD

**Issue by zgq91** [chenbq1234/Gnu-RL#2]
Hi:
   Control the central air conditioning temperature constant, how to use the cooling water temperature, frozen water temperature, outdoor temperature, water flow rate and other data training model

**Comment by bingqingchen** [comment]
Hi, this repo is about HVAC control. I am using a co-simulation environment developed by someone else, [Gym-Eplus](https://github.com/zhangzhizza/Gym-Eplus). I would suggest you check with its author, regarding how to extend the co-simulation environment.
